from datetime import datetime
from apps.app import db


class exRate(db.Model):
    __tablename__ = "ex_rate"
    id = db.Column(db.Integer, primary_key=True)
    version = db.Column(db.String(12)) #, db.ForeignKey("version.version"))
    year = db.Column(db.String(4))
    mm = db.Column(db.String(2))
    curr = db.Column(db.String(3))
    rate = db.Column(db.Numeric(precision=22, scale=2))
    user_id = db.Column(db.Integer)
    create_at = db.Column(db.DateTime, default = datetime.now)


class IncomeState(db.Model):
    __tablename__ = "test_excel2"
    id = db.Column(db.Integer, primary_key=True)
    version = db.Column(db.String(12)) #, db.ForeignKey("version.version"))
    year = db.Column(db.String(4))
    mm = db.Column(db.String(2))
    company = db.Column(db.String(4))
    curr = db.Column(db.String(3))
    Sales = db.Column(db.Numeric(precision=22, scale=2))
    CGS = db.Column(db.Numeric(precision=22, scale=2))
    CGM = db.Column(db.Numeric(precision=22, scale=2))
    Freight = db.Column(db.Numeric(precision=22, scale=2))
    Insure_ex = db.Column(db.Numeric(precision=22, scale=2))
    GP = db.Column(db.Numeric(precision=22, scale=2))
    SalesExpences = db.Column(db.Numeric(precision=22, scale=2))
    Agent_ex = db.Column(db.Numeric(precision=22, scale=2))
    Agent_inland = db.Column(db.Numeric(precision=22, scale=2))
    Moving_ex = db.Column(db.Numeric(precision=22, scale=2))
    Moving_inland = db.Column(db.Numeric(precision=22, scale=2))
    Insure_PL = db.Column(db.Numeric(precision=22, scale=2))
    Comp_ex = db.Column(db.Numeric(precision=22, scale=2))
    Comp_inland = db.Column(db.Numeric(precision=22, scale=2))
    Packing_ex = db.Column(db.Numeric(precision=22, scale=2))
    Packing_inland = db.Column(db.Numeric(precision=22, scale=2))
    Royalty_inland = db.Column(db.Numeric(precision=22, scale=2))
    Royalty_ex = db.Column(db.Numeric(precision=22, scale=2))
    Advertisement_ex = db.Column(db.Numeric(precision=22, scale=2))
    Advertisement_inland = db.Column(db.Numeric(precision=22, scale=2))
    OperatingProfit1 = db.Column(db.Numeric(precision=22, scale=2))
    AdminExpences = db.Column(db.Numeric(precision=22, scale=2))
    SalaryBOD = db.Column(db.Numeric(precision=22, scale=2))
    Salary = db.Column(db.Numeric(precision=22, scale=2))
    Pension = db.Column(db.Numeric(precision=22, scale=2))
    EmployBenefit = db.Column(db.Numeric(precision=22, scale=2))
    Travel = db.Column(db.Numeric(precision=22, scale=2))
    Telecommunication = db.Column(db.Numeric(precision=22, scale=2))
    Utilities = db.Column(db.Numeric(precision=22, scale=2))
    TaxesAndDues = db.Column(db.Numeric(precision=22, scale=2))
    Rent = db.Column(db.Numeric(precision=22, scale=2))
    Depreciation = db.Column(db.Numeric(precision=22, scale=2))
    Amortization = db.Column(db.Numeric(precision=22, scale=2))
    Maintanance = db.Column(db.Numeric(precision=22, scale=2))
    Insurance = db.Column(db.Numeric(precision=22, scale=2))
    Entertainment = db.Column(db.Numeric(precision=22, scale=2))
    SampleFee = db.Column(db.Numeric(precision=22, scale=2))
    TransportFee = db.Column(db.Numeric(precision=22, scale=2))
    Commission = db.Column(db.Numeric(precision=22, scale=2))
    Service = db.Column(db.Numeric(precision=22, scale=2))
    BedDept = db.Column(db.Numeric(precision=22, scale=2))
    Consumable = db.Column(db.Numeric(precision=22, scale=2))
    Training = db.Column(db.Numeric(precision=22, scale=2))
    BooksAndPrinting = db.Column(db.Numeric(precision=22, scale=2))
    Vehicle = db.Column(db.Numeric(precision=22, scale=2))
    Conference = db.Column(db.Numeric(precision=22, scale=2))
    Miscellaneous = db.Column(db.Numeric(precision=22, scale=2))
    Overseas = db.Column(db.Numeric(precision=22, scale=2))
    Warehouse = db.Column(db.Numeric(precision=22, scale=2))
    ReversalBadDebt = db.Column(db.Numeric(precision=22, scale=2))
    ResearchDevelopment = db.Column(db.Numeric(precision=22, scale=2))
    LeaseAmortization = db.Column(db.Numeric(precision=22, scale=2))
    OperatingProfit2 = db.Column(db.Numeric(precision=22, scale=2))
    NonOperatingRevenue = db.Column(db.Numeric(precision=22, scale=2))
    FinancialRevenue = db.Column(db.Numeric(precision=22, scale=2))
    InterestRevenue = db.Column(db.Numeric(precision=22, scale=2))
    TradingSecuritiesInterest = db.Column(db.Numeric(precision=22, scale=2))
    FxRevenue = db.Column(db.Numeric(precision=22, scale=2))
    FxRevenue_Operating = db.Column(db.Numeric(precision=22, scale=2))
    FxIncone_NonOp = db.Column(db.Numeric(precision=22, scale=2))
    DerivativesRevenue = db.Column(db.Numeric(precision=22, scale=2))
    TradingSecuritiesRevenue = db.Column(db.Numeric(precision=22, scale=2))
    OtherNonOPRevenue = db.Column(db.Numeric(precision=22, scale=2))
    DividentRevenue = db.Column(db.Numeric(precision=22, scale=2))
    MiscellaneousProfit = db.Column(db.Numeric(precision=22, scale=2))
    Gain_disposal_assets = db.Column(db.Numeric(precision=22, scale=2))
    Gain_OtherNonOP = db.Column(db.Numeric(precision=22, scale=2))
    ReversalNRV = db.Column(db.Numeric(precision=22, scale=2))
    ReversalOtherAllowance = db.Column(db.Numeric(precision=22, scale=2))
    NonOperatingEnpences = db.Column(db.Numeric(precision=22, scale=2))
    FinancialCost = db.Column(db.Numeric(precision=22, scale=2))
    Interest = db.Column(db.Numeric(precision=22, scale=2))
    BondInterest = db.Column(db.Numeric(precision=22, scale=2))
    LossDisposalAR = db.Column(db.Numeric(precision=22, scale=2))
    FxLoss = db.Column(db.Numeric(precision=22, scale=2))
    FxLoss_Operating = db.Column(db.Numeric(precision=22, scale=2))
    FxLoss_NonOP = db.Column(db.Numeric(precision=22, scale=2))
    DerivativesLoss_tot = db.Column(db.Numeric(precision=22, scale=2))
    DerivativesLoss = db.Column(db.Numeric(precision=22, scale=2))
    TradingSecuritiesLoss = db.Column(db.Numeric(precision=22, scale=2))
    OtherNonOPLoss = db.Column(db.Numeric(precision=22, scale=2))
    Donation = db.Column(db.Numeric(precision=22, scale=2))
    Loss_disposal_assets = db.Column(db.Numeric(precision=22, scale=2))
    Loss_disposal_inventory = db.Column(db.Numeric(precision=22, scale=2))
    Loss_OtherNonOP = db.Column(db.Numeric(precision=22, scale=2))
    MiscellaneousLoss = db.Column(db.Numeric(precision=22, scale=2))
    OtherAllowance = db.Column(db.Numeric(precision=22, scale=2))
    OrdinaryIncome1 = db.Column(db.Numeric(precision=22, scale=2))
    Gain_disposal_assets_NonOP = db.Column(db.Numeric(precision=22, scale=2))
    DebtForgiveness = db.Column(db.Numeric(precision=22, scale=2))
    LeaseInterestIncome = db.Column(db.Numeric(precision=22, scale=2))
    OtherSpecialGain = db.Column(db.Numeric(precision=22, scale=2))
    Loss_disposal_assets_NonOP = db.Column(db.Numeric(precision=22, scale=2))
    DebtForgivenessAmortization = db.Column(db.Numeric(precision=22, scale=2))
    LeaseInterestCost = db.Column(db.Numeric(precision=22, scale=2))
    OtherSpecialLoss = db.Column(db.Numeric(precision=22, scale=2))
    ValuationLoss = db.Column(db.Numeric(precision=22, scale=2))
    OrdinaryIncome2 = db.Column(db.Numeric(precision=22, scale=2))
    FxValuation = db.Column(db.Numeric(precision=22, scale=2))
    FxValuationGain_OP = db.Column(db.Numeric(precision=22, scale=2))
    FxValuationGain_NonOP = db.Column(db.Numeric(precision=22, scale=2))
    FxValuationLoss_OP = db.Column(db.Numeric(precision=22, scale=2))
    FxValuationLoss_NonOP = db.Column(db.Numeric(precision=22, scale=2))
    DerivativesVauation = db.Column(db.Numeric(precision=22, scale=2))
    DerivativesVauationGain = db.Column(db.Numeric(precision=22, scale=2))
    DerivativesVauationLoss = db.Column(db.Numeric(precision=22, scale=2))
    OrdinaryIncome3 = db.Column(db.Numeric(precision=22, scale=2))
    SecuritiesGain = db.Column(db.Numeric(precision=22, scale=2))
    SecuritiesLoss = db.Column(db.Numeric(precision=22, scale=2))
    OrdinaryIncome4 = db.Column(db.Numeric(precision=22, scale=2))
    Tax = db.Column(db.Numeric(precision=22, scale=2))
    NetIncome = db.Column(db.Numeric(precision=22, scale=2))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    create_at = db.Column(db.DateTime, default = datetime.now)


class version(db.Model):
    __tablename__ = "version"
    id = db.Column(db.Integer, primary_key=True)
    year = db.Column(db.String(4))
    mm = db.Column(db.String(2))
    tomm = db.Column(db.String(2))
    version = db.Column(db.String(12))
    created_at = db.Column(db.DateTime, default = datetime.now)
    __table_args__ = (db.UniqueConstraint('year','mm','version'),)


class currentVersion(db.Model):
    __tablename__ = "curVer"
    id = db.Column(db.Integer, primary_key=True)
    version = db.Column(db.String(12))
    year = db.Column(db.String(4))
    selectedMM = db.Column(db.String(2))
    toMM = db.Column(db.String(2))
    company = db.Column(db.String(4))
    

class salesEstimate(db.Model):
    __tablename__ = "salesplan"
    id = db.Column(db.Integer, primary_key=True)
    version = db.Column(db.String(12))
    year = db.Column(db.String(4))
    mm = db.Column(db.String(2))
    salesDivision = db.Column(db.String(20))
    amount_EA = db.Column(db.Numeric(precision=22, scale=2))
    amount_weight = db.Column(db.Numeric(precision=22, scale=2))
    amount_sales = db.Column(db.Numeric(precision=22, scale=2))
    created_at = db.Column(db.DateTime, default = datetime.now)
    __table_args__ = (db.UniqueConstraint('version','year','mm','salesDivision',),)


class specialThings(db.Model):
    __tablename__ = "dontForget"
    id = db.Column(db.Integer, primary_key=True)
    year = db.Column(db.String(4))
    content = db.Column(db.String(200))
    description = db.Column(db.String(200))
    finished = db.Column(db.String(1))
    amt_tot = db.Column(db.Numeric(precision=22, scale=2),default=0)
    amt_jan = db.Column(db.Numeric(precision=22, scale=2),default=0)
    amt_feb = db.Column(db.Numeric(precision=22, scale=2),default=0)
    amt_mar = db.Column(db.Numeric(precision=22, scale=2),default=0)
    amt_apr = db.Column(db.Numeric(precision=22, scale=2),default=0)
    amt_may = db.Column(db.Numeric(precision=22, scale=2),default=0)
    amt_jun = db.Column(db.Numeric(precision=22, scale=2),default=0)
    amt_jul = db.Column(db.Numeric(precision=22, scale=2),default=0)
    amt_aug = db.Column(db.Numeric(precision=22, scale=2),default=0)
    amt_sep = db.Column(db.Numeric(precision=22, scale=2),default=0)
    amt_oct = db.Column(db.Numeric(precision=22, scale=2),default=0)
    amt_nov = db.Column(db.Numeric(precision=22, scale=2),default=0)
    amt_dec = db.Column(db.Numeric(precision=22, scale=2),default=0)
    created_at = db.Column(db.DateTime, default = datetime.now)


class checkProcedure(db.Model):
    __tablename__ = "procedure"
    id = db.Column(db.Integer, primary_key=True)
    version = db.Column(db.String(12))
    fxinput = db.Column(db.String(1))
    fxfinish = db.Column(db.String(1))
    getttl = db.Column(db.String(1))
    getothers = db.Column(db.String(1)) 
    getfinal = db.Column(db.String(1))
    user_id = db.Column(db.Integer)
    create_at = db.Column(db.DateTime, default = datetime.now)
    __table_args__ = (db.UniqueConstraint('version'),)


class eliminate(db.Model):
    __tablename__ = "elimination"
    id = db.Column(db.Integer, primary_key=True)
    version = db.Column(db.String(12))
    content = db.Column(db.String(200))
    account = db.Column(db.String(200))
    jan = db.Column(db.Numeric(precision=22, scale=2),default=0)
    feb = db.Column(db.Numeric(precision=22, scale=2),default=0)
    mar = db.Column(db.Numeric(precision=22, scale=2),default=0)
    apr = db.Column(db.Numeric(precision=22, scale=2),default=0)
    may = db.Column(db.Numeric(precision=22, scale=2),default=0)
    jun = db.Column(db.Numeric(precision=22, scale=2),default=0)
    jul = db.Column(db.Numeric(precision=22, scale=2),default=0)
    aug = db.Column(db.Numeric(precision=22, scale=2),default=0)
    sep = db.Column(db.Numeric(precision=22, scale=2),default=0)
    oct = db.Column(db.Numeric(precision=22, scale=2),default=0)
    nov = db.Column(db.Numeric(precision=22, scale=2),default=0)
    dec = db.Column(db.Numeric(precision=22, scale=2),default=0)
    tot_month = db.Column(db.Numeric(precision=22, scale=2),default=0)
    source = db.Column(db.String(20))
    created_at = db.Column(db.DateTime, default = datetime.now)


class COA(db.Model):
    __tablename__ = "account_group"
    id = db.Column(db.Integer, primary_key=True)
    lv1 = db.Column(db.String(200))
    account = db.Column(db.String(200))
